default_platform(:ios)

platform :ios do

  desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch")
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  def release(type)
    update_fastlane
    podspecName = "UpdraftSDK.podspec"
    ensure_git_branch
    ensure_git_status_clean
    pod_lib_lint
    version = version_bump_podspec(path: podspecName, bump_type: type)
    git_add(path: podspecName)
    git_commit(path: [podspecName], message: "#{version} release")
    add_git_tag(tag: "#{version}")
    push_to_git_remote
    pod_push(allow_warnings: true, verbose: true)
  end
end